# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DoEnKF <- function(a, b) {
    .Call('EnKF4_0720_DoEnKF', PACKAGE = 'EnKF4_0720', a, b)
}

